// Files the service worker caches at install, so the app starts and imports a word list offline.
// It is a second copy of the app's file layout: tests/precache.test.js crawls the module graph
// from index.html and fails when a file is missing here.
self.PRECACHE_URLS = [
    './',
    'index.html',
    'manifest.webmanifest',
    'css/app.css',
    'icons/icon-192.png',
    'icons/icon-512.png',
    'icons/apple-touch-icon.png',
    'vendor/xlsx.full.min.js',
    'js/main.js',
    'js/core/choices.js',
    'js/core/matching.js',
    'js/core/session.js',
    'js/core/shuffle.js',
    'js/core/stats.js',
    'js/core/text.js',
    'js/data/deck.js',
    'js/data/import-profiles.js',
    'js/data/importer.js',
    'js/data/languages.js',
    'js/data/storage.js',
    'js/i18n/index.js',
    'js/i18n/uk.js',
    'js/platform/keys.js',
    'js/platform/speech.js',
    'js/ui/dom.js',
    'js/ui/labels.js',
    'js/ui/modes/choice.js',
    'js/ui/modes/flashcards.js',
    'js/ui/modes/matching.js',
    'js/ui/modes/registry.js',
    'js/ui/screens/session.js',
    'js/ui/screens/start.js',
    'js/ui/screens/stats.js',
];
